export default {
    table: true,
    teamsNumber: 16,
    teams: [
        {
            id: 't0',
            name: 1,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
            isStaying: true,
        },
        {
            id: 't1',
            name: 2,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
        },
        {
            id: 't2',
            name: 3,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
        },
        {
            id: 't3',
            name: 4,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
            isStaying: true,
        },
        {
            id: 't4',
            name: 5,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
            isStaying: true,
        },
        {
            id: 't5',
            name: 6,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
        },
        {
            id: 't6',
            name: 7,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
            isStaying: true,
        },
        {
            id: 't7',
            name: 8,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
        },
        {
            id: 't8',
            name: 9,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
            isStaying: true,
        },
        {
            id: 't9',
            name: 10,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
            isStaying: true,
        },
        {
            id: 't10',
            name: 11,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
            isStaying: true,
        },
        {
            id: 't11',
            name: 12,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
        },
        {
            id: 't12',
            name: 13,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
        },
        {
            id: 't13',
            name: 14,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
        },
        {
            id: 't14',
            name: 15,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
        },
        {
            id: 't15',
            name: 16,
            tableTurn: 0,
            sets: [
                'x',
                'x',
                'x',
                'x',
            ],
        },
    ],
};
